using System.Text.Json;

namespace Napkin.Assistant.LocalServer.Tests;

/// <summary>
/// Reply bodies written by hand in the shapes the two programs document — never recorded from a
/// running program or a model. The shapes were read on 2026-09-27 from:
/// <list type="bullet">
/// <item><description>Ollama: https://github.com/ollama/ollama/blob/main/docs/api.md ("List Local
/// Models", "Show Model Information", "Chat request (No streaming)"),
/// https://github.com/ollama/ollama/blob/main/docs/openapi.yaml (<c>ModelSummary</c>'s
/// <c>remote_model</c> and <c>remote_host</c>, <c>ShowResponse</c>'s <c>license</c>) and
/// https://github.com/ollama/ollama/blob/main/docs/api/errors.mdx (<c>{"error": "…"}</c>).</description></item>
/// <item><description>llama.cpp's server: https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md
/// ("GET /v1/models", "POST /v1/chat/completions" — <c>choices[0].message</c> — and "API errors").</description></item>
/// </list>
/// The sizes, digests and dates in them are made up for the tests; only the field names and
/// nesting are the documented ones.
/// </summary>
public static class Documented
{
    /// <summary>
    /// <c>GET /api/tags</c>: one local model in the docs' shape, and one remote model carrying the
    /// openapi.yaml's <c>remote_model</c> and <c>remote_host</c>.
    /// </summary>
    public const string OllamaTags = """
        {
          "models": [
            {
              "name": "qwen3:4b-q4_K_M",
              "model": "qwen3:4b-q4_K_M",
              "modified_at": "2026-09-20T08:06:48.639712648-04:00",
              "size": 2620788019,
              "digest": "2bfd38a7daaf0000000000000000000000000000000000000000000000000000",
              "details": {
                "parent_model": "",
                "format": "gguf",
                "family": "qwen3",
                "families": ["qwen3"],
                "parameter_size": "4.0B",
                "quantization_level": "Q4_K_M"
              }
            },
            {
              "name": "gpt-oss:120b-cloud",
              "model": "gpt-oss:120b-cloud",
              "remote_model": "gpt-oss:120b",
              "remote_host": "https://ollama.com:443",
              "modified_at": "2026-09-21T09:00:00.000000000-04:00",
              "size": 384,
              "digest": "0000000000000000000000000000000000000000000000000000000000000000",
              "details": {
                "parent_model": "",
                "format": "",
                "family": "gptoss",
                "families": ["gptoss"],
                "parameter_size": "116.8B",
                "quantization_level": "MXFP4"
              }
            }
          ]
        }
        """;

    /// <summary>
    /// <c>POST /api/show</c> in the docs' shape, with <c>license</c> (openapi.yaml: "The license of the
    /// model") holding the opening lines of the Apache License 2.0 as a model's license text does.
    /// </summary>
    public const string OllamaShow = """
        {
          "license": "                                 Apache License\n                           Version 2.0, January 2004\n                        http://www.apache.org/licenses/\n\n   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION\n",
          "modelfile": "# Modelfile generated by \"ollama show\"",
          "parameters": "repeat_penalty 1\nstop \"<|im_start|>\"",
          "template": "{{- range $i, $_ := .Messages }}",
          "details": {
            "parent_model": "",
            "format": "gguf",
            "family": "qwen3",
            "families": ["qwen3"],
            "parameter_size": "4.0B",
            "quantization_level": "Q4_K_M"
          },
          "model_info": {
            "general.architecture": "qwen3",
            "general.file_type": 15,
            "general.parameter_count": 4022468096,
            "qwen3.context_length": 40960,
            "qwen3.embedding_length": 2560
          },
          "capabilities": ["completion", "tools", "thinking"]
        }
        """;

    /// <summary><c>GET /v1/models</c> in the README's shape: one element, <c>id</c> the model file's path.</summary>
    public const string LlamaModels = """
        {
          "object": "list",
          "data": [
            {
              "id": "../models/Qwen3-4B-Q4_K_M.gguf",
              "object": "model",
              "created": 1735142223,
              "owned_by": "llamacpp",
              "meta": {
                "vocab_type": 2,
                "n_vocab": 151936,
                "n_ctx_train": 40960,
                "n_embd": 2560,
                "n_params": 4022468096,
                "size": 2497280256
              }
            }
          ]
        }
        """;

    /// <summary><c>GET /v1/models</c> while the model loads: "The <c>meta</c> field can be <c>null</c>".</summary>
    public const string LlamaModelsLoading = """
        {"object": "list", "data": [{"id": "qwen3-4b", "object": "model", "created": 1735142223, "owned_by": "llamacpp", "meta": null}]}
        """;

    /// <summary>Ollama's error body (docs/api/errors.mdx).</summary>
    public static string OllamaError(string message) => JsonSerializer.Serialize(new { error = message });

    /// <summary>llama-server's error body (README "API errors": "the same format as OAI").</summary>
    public static string OpenAiError(int code, string message, string type) =>
        JsonSerializer.Serialize(new { error = new { code, message, type } });

    /// <summary><c>POST /api/chat</c> with <c>"stream": false</c>: one object, the answer in <c>message.content</c>.</summary>
    public static string OllamaChat(string content) => JsonSerializer.Serialize(new
    {
        model = "qwen3:4b-q4_K_M",
        created_at = "2026-09-27T14:13:43.416799Z",
        message = new { role = "assistant", content },
        done_reason = "stop",
        done = true,
        total_duration = 5191566416,
        load_duration = 2154458,
        prompt_eval_count = 26,
        prompt_eval_duration = 383809000,
        eval_count = 298,
        eval_duration = 4799921000,
    });

    /// <summary><c>POST /v1/chat/completions</c>: the answer in <c>choices[0].message.content</c>, with the README's <c>usage</c> and <c>timings</c>.</summary>
    public static string OpenAiChat(string content) => JsonSerializer.Serialize(new
    {
        choices = new[] { new { finish_reason = "stop", index = 0, message = new { role = "assistant", content } } },
        created = 1757141666,
        id = "chatcmpl-ecQULm0WqPrftUqjPZO1CFYeDjGZNbDu",
        model = "qwen3-4b",
        @object = "chat.completion",
        usage = new { completion_tokens = 48, prompt_tokens = 44, total_tokens = 92 },
        timings = new { cache_n = 236, prompt_n = 1, predicted_n = 35 },
    });
}
