using System.Text;

namespace Napkin.Tools.Features;

/// <summary>
/// Writes one skipped fact per catalogued feature that no hand-written test claims yet, so the
/// generated file *is* the checklist: delete a stub by writing the real test.
/// </summary>
/// <remarks>
/// The generator reads hand-written claims only — files ending in `.g.cs` are skipped — so it
/// never counts its own output as evidence that a feature is covered. Output is sorted by id and
/// carries no timestamp, so regenerating without a catalog change produces a byte-identical file.
/// </remarks>
public static class StubGenerator
{
    /// <summary>The namespace the generated class lives in.</summary>
    public const string Namespace = "Napkin.Features.Tests";

    /// <summary>The generated class name.</summary>
    public const string ClassName = "PlannedFeatures";

    /// <summary>
    /// Renders the file. <paramref name="handWrittenClaims"/> must already exclude `*.g.cs`.
    /// </summary>
    public static string Render(Catalog catalog, IReadOnlyList<FeatureClaim> handWrittenClaims)
    {
        var claimed = handWrittenClaims
            .Select(claim => claim.FeatureId)
            .ToHashSet(StringComparer.Ordinal);

        var planned = catalog.Features
            .Where(feature => !claimed.Contains(feature.Id))
            .OrderBy(feature => feature.Id, StringComparer.Ordinal)
            .ToList();

        var source = new StringBuilder();
        source.Append("// <auto-generated>\n");
        source.Append("//     Generated by:\n");
        source.Append("//         dotnet run --project tools/Napkin.Tools -- scorecard stubs\n");
        source.Append("//\n");
        source.Append("//     One skipped fact per catalogued feature that no hand-written test claims yet\n");
        source.Append("//     (issue #34). The list of stubs is the checklist: when a feature gets a real\n");
        source.Append("//     test carrying its [Trait(\"Feature\", \"<ID>\")], regenerate and its stub goes away.\n");
        source.Append("//     Edit features/*.json, never this file.\n");
        source.Append("// </auto-generated>\n");
        source.Append('\n');
        source.Append($"namespace {Namespace};\n");
        source.Append('\n');
        source.Append($"public class {ClassName}\n");
        source.Append("{\n");

        if (planned.Count == 0)
        {
            source.Append(catalog.Features.Count == 0
                ? "    // The feature catalog under features/ is empty, so there is nothing to plan yet.\n"
                : "    // Every catalogued feature has a hand-written test. Nothing to plan.\n");
        }

        for (var index = 0; index < planned.Count; index++)
        {
            if (index > 0)
            {
                source.Append('\n');
            }

            var feature = planned[index];
            source.Append($"    [Fact(Skip = \"{Escape($"planned: {feature.Id} — {feature.Title}")}\")]\n");
            source.Append($"    [Trait(\"{TraitScanner.TraitName}\", \"{Escape(feature.Id)}\")]\n");
            source.Append($"    public void {MethodName(feature.Id)}()\n");
            source.Append("    {\n");
            source.Append("    }\n");
        }

        source.Append("}\n");
        return source.ToString();
    }

    /// <summary>
    /// Writes the file only when its content changed, so a no-op regeneration leaves the working
    /// tree clean. Returns true when something was written.
    /// </summary>
    public static bool Write(string path, string content)
    {
        var encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: true);
        var normalized = content.ReplaceLineEndings("\n");
        if (File.Exists(path) && File.ReadAllText(path) == normalized)
        {
            return false;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        File.WriteAllText(path, normalized, encoding);
        return true;
    }

    /// <summary>`GEO-LEN-001` becomes `GEO_LEN_001`; an id starting with a digit gets a `_`.</summary>
    public static string MethodName(string featureId)
    {
        var name = new StringBuilder(featureId.Length);
        foreach (var character in featureId)
        {
            name.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        if (name.Length == 0 || !(char.IsLetter(name[0]) || name[0] == '_'))
        {
            name.Insert(0, '_');
        }

        return name.ToString();
    }

    /// <summary>Makes a catalog title safe inside a C# string literal.</summary>
    private static string Escape(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\r", string.Empty, StringComparison.Ordinal)
        .Replace("\n", " ", StringComparison.Ordinal);
}
