<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Napkin.Core.Geometry\Napkin.Core.Geometry.csproj" />
    <ProjectReference Include="..\Napkin.Core.Materials\Napkin.Core.Materials.csproj" />
    <ProjectReference Include="..\Napkin.Core.Project\Napkin.Core.Project.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
