// <auto-generated>
//     Generated by:
//         dotnet run --project tools/Napkin.Tools -- scorecard stubs
//
//     One skipped fact per catalogued feature that no hand-written test claims yet
//     (issue #34). The list of stubs is the checklist: when a feature gets a real
//     test carrying its [Trait("Feature", "<ID>")], regenerate and its stub goes away.
//     Edit features/*.json, never this file.
// </auto-generated>

namespace Napkin.Features.Tests;

public class PlannedFeatures
{
    // The feature catalog under features/ is empty, so there is nothing to plan yet.
}
