// <auto-generated>
//     Generated by:
//         dotnet run --project tools/Napkin.Tools -- scorecard stubs
//
//     One skipped fact per catalogued feature that no hand-written test claims yet
//     (issue #34). The list of stubs is the checklist: when a feature gets a real
//     test carrying its [Trait("Feature", "<ID>")], regenerate and its stub goes away.
//     Edit features/*.json, never this file.
// </auto-generated>

namespace Napkin.Features.Tests;

public class PlannedFeatures
{
    [Fact(Skip = "planned: CODE-001 — Connecticut 2026 header and fastener tables")]
    [Trait("Feature", "CODE-001")]
    public void CODE_001()
    {
    }

    [Fact(Skip = "planned: CODE-002 — Connecticut 2026 boundary rows flip cleanly")]
    [Trait("Feature", "CODE-002")]
    public void CODE_002()
    {
    }

    [Fact(Skip = "planned: CODE-003 — Connecticut 2026 bracing provisions")]
    [Trait("Feature", "CODE-003")]
    public void CODE_003()
    {
    }

    [Fact(Skip = "planned: CODE-004 — Connecticut 2022 pack")]
    [Trait("Feature", "CODE-004")]
    public void CODE_004()
    {
    }

    [Fact(Skip = "planned: CODE-005 — Massachusetts 780 CMR residential pack")]
    [Trait("Feature", "CODE-005")]
    public void CODE_005()
    {
    }

    [Fact(Skip = "planned: CODE-006 — Pennsylvania Uniform Construction Code pack")]
    [Trait("Feature", "CODE-006")]
    public void CODE_006()
    {
    }

    [Fact(Skip = "planned: CODE-007 — A municipal overlay changes only what it amends")]
    [Trait("Feature", "CODE-007")]
    public void CODE_007()
    {
    }

    [Fact(Skip = "planned: CVS-010 — Display precision is per project, and inexact display is marked")]
    [Trait("Feature", "CVS-010")]
    public void CVS_010()
    {
    }

    [Fact(Skip = "planned: GUI-CUT-01 — Build the coffee table end to end")]
    [Trait("Feature", "GUI-CUT-01")]
    public void GUI_CUT_01()
    {
    }

    [Fact(Skip = "planned: GUI-PORCH-02 — Build the worked example's porch end to end")]
    [Trait("Feature", "GUI-PORCH-02")]
    public void GUI_PORCH_02()
    {
    }

    [Fact(Skip = "planned: IOP-003 — PDF sheets are vector and true scale, with a title block")]
    [Trait("Feature", "IOP-003")]
    public void IOP_003()
    {
    }

    [Fact(Skip = "planned: PKG-001 — Self-contained builds start on a clean machine")]
    [Trait("Feature", "PKG-001")]
    public void PKG_001()
    {
    }

    [Fact(Skip = "planned: PKG-002 — First-run instructions and the source offer ship with every build")]
    [Trait("Feature", "PKG-002")]
    public void PKG_002()
    {
    }

    [Fact(Skip = "planned: PRJ-006 — The project is a documented zip container")]
    [Trait("Feature", "PRJ-006")]
    public void PRJ_006()
    {
    }

    [Fact(Skip = "planned: REL-001 — A tag produces downloadable macOS and Windows artifacts")]
    [Trait("Feature", "REL-001")]
    public void REL_001()
    {
    }

    [Fact(Skip = "planned: REL-003 — The arm64 macOS artifact carries its ad-hoc signature only")]
    [Trait("Feature", "REL-003")]
    public void REL_003()
    {
    }

    [Fact(Skip = "planned: SITE-001 — A survey underlay calibrates from two known points")]
    [Trait("Feature", "SITE-001")]
    public void SITE_001()
    {
    }

    [Fact(Skip = "planned: SITE-002 — Property lines and setbacks measure against structures")]
    [Trait("Feature", "SITE-002")]
    public void SITE_002()
    {
    }

    [Fact(Skip = "planned: SITE-003 — North arrow and sheet orientation are stored with the project")]
    [Trait("Feature", "SITE-003")]
    public void SITE_003()
    {
    }

    [Fact(Skip = "planned: SOLV-001 — Angled golden cases solve and verify")]
    [Trait("Feature", "SOLV-001")]
    public void SOLV_001()
    {
    }

    [Fact(Skip = "planned: SOLV-002 — The solver is no worse on the direct updater's own domain")]
    [Trait("Feature", "SOLV-002")]
    public void SOLV_002()
    {
    }

    [Fact(Skip = "planned: SOLV-003 — Solver conflict reports name relationships worth removing")]
    [Trait("Feature", "SOLV-003")]
    public void SOLV_003()
    {
    }
}
